"""
Generates a human-readable credit assessment report using Ollama + Llama 3 (local, free).

Prerequisites:
    1. Install Ollama: brew install ollama   (or https://ollama.com/download)
    2. Pull model:    ollama pull llama3
    3. Start server:  ollama serve           (runs on http://localhost:11434)

If Ollama is not available, falls back to a rule-based template report.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL = "llama3"

# Also check local bin/ in case Ollama was installed by setup.py
_LOCAL_OLLAMA = os.path.join(os.path.dirname(os.path.dirname(__file__)), "bin", "ollama")


def _rule_based_report(msme_name, credit_score, risk_tier, sub_scores, positive_factors, negative_factors) -> str:
    """Fallback template when Ollama is unavailable."""
    strengths = ", ".join([f["label"] for f in positive_factors]) if positive_factors else "None identified"
    risks = ", ".join([f["label"] for f in negative_factors]) if negative_factors else "None identified"

    if risk_tier == "Low Risk":
        recommendation = "APPROVE — The business demonstrates strong financial discipline and operational reliability."
    elif risk_tier == "Medium Risk":
        recommendation = (
            "CONDITIONAL APPROVAL — Consider requiring additional collateral or a shorter loan tenure. "
            "Monitor repayment closely."
        )
    else:
        recommendation = (
            "DECLINE / HIGH SCRUTINY — Significant risk indicators are present. "
            "Do not approve without comprehensive due diligence and strong collateral."
        )

    return f"""
CREDIT ASSESSMENT REPORT
========================
MSME Name     : {msme_name}
Credit Score  : {credit_score:.1f} / 100
Risk Tier     : {risk_tier}

SUB-SCORES
----------
  GST Compliance        : {sub_scores['gst']:.1f} / 100
  Payment Behaviour     : {sub_scores['payment']:.1f} / 100
  Marketplace Performance: {sub_scores['marketplace']:.1f} / 100

EXECUTIVE SUMMARY
-----------------
{msme_name} has been assessed with a composite credit score of {credit_score:.1f}/100, placing it in the
{risk_tier} category. This evaluation is based on alternative data signals including GST compliance,
marketplace performance metrics, and payment behaviour history.

STRENGTHS
---------
{strengths}

RISK CONCERNS
-------------
{risks}

RECOMMENDATION
--------------
{recommendation}

Note: This report is generated by an automated system and should be reviewed by a qualified credit analyst.
""".strip()


def generate_credit_report(
    msme_name: str,
    credit_score: float,
    risk_tier: str,
    sub_scores: dict,
    positive_factors: list,
    negative_factors: list,
) -> str:
    """
    Generate a credit assessment report.

    Args:
        msme_name: Business name
        credit_score: Composite score 0-100
        risk_tier: "Low Risk" / "Medium Risk" / "High Risk"
        sub_scores: {"gst": float, "payment": float, "marketplace": float}
        positive_factors: list of factor dicts with "label" key
        negative_factors: list of factor dicts with "label" key

    Returns:
        Formatted credit assessment report string
    """
    pos_text = ", ".join([f["label"] for f in positive_factors]) if positive_factors else "None identified"
    neg_text = ", ".join([f["label"] for f in negative_factors]) if negative_factors else "None identified"

    prompt = f"""You are a senior credit analyst at an Indian MSME lending institution.
Write a professional credit assessment report for the following e-commerce MSME.
Be concise but thorough. Use plain English — no markdown headers.

Business Name: {msme_name}
Credit Risk Score: {credit_score:.1f} out of 100
Risk Tier: {risk_tier}

Sub-scores:
- GST Compliance Score: {sub_scores['gst']:.1f}/100
- Payment Behaviour Score: {sub_scores['payment']:.1f}/100
- Marketplace Performance Score: {sub_scores['marketplace']:.1f}/100

Key Strengths (factors that improve creditworthiness): {pos_text}
Key Risk Factors (factors that reduce creditworthiness): {neg_text}

Structure your report as follows:
1. Executive Summary (2-3 sentences summarising the overall credit profile)
2. Strengths Analysis (explain each strength and why it matters)
3. Risk Concerns (explain each risk factor and its implication)
4. Lending Recommendation (Approve / Conditional Approval / Decline) with clear reasoning and suggested loan conditions if applicable

Do NOT use bullet points. Write in professional paragraph form.
"""

    try:
        # Use streaming to avoid read timeouts on long generations
        response = requests.post(
            OLLAMA_URL,
            json={"model": MODEL, "prompt": prompt, "stream": True},
            stream=True,
            timeout=30,   # connection timeout only; streaming keeps the socket alive
        )
        response.raise_for_status()

        import json as _json
        chunks = []
        for line in response.iter_lines():
            if line:
                chunk = _json.loads(line)
                chunks.append(chunk.get("response", ""))
                if chunk.get("done"):
                    break
        return "".join(chunks).strip()
    except Exception:
        return _rule_based_report(
            msme_name, credit_score, risk_tier, sub_scores, positive_factors, negative_factors
        )
